@BCBCTI_HostAddress = http://localhost:5000

GET {{BCBCTI_HostAddress}}/taxii2/
Accept: application/json

###

GET {{BCBCTI_HostAddress}}/api/
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/
Accept: application/taxii+json;version=2.1


###

GET {{BCBCTI_HostAddress}}/api/collections/1e9a75e0-0a6b-412f-a445-fb050f3523b7
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/1e9a75e0-0a6b-512f-a445-fb050f3523b7
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/default
Accept: application/taxii+json;version=2.1

### Create new objects

POST {{BCBCTI_HostAddress}}/api/collections/default
Accept: application/taxii+json;version=2.1
Content-Type: application/taxii+json;version=2.1

{
	"objects": [
		{
			"type": "threat-actor",
			"spec_version": "2.1",
			"id": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
			"created": "2014-11-19T23:39:03.893Z",
			"modified": "2014-11-19T23:39:03.893Z",
			"name": "Disco Team Threat Actor Group",
			"description": "This organized threat actor group operates to create profit from all types of crime.",
			"threat_actor_types": [
				"crime-syndicate"
			],
			"aliases": [
				"Equipo del Discoteca"
			],
			"roles": [
				"agent"
			],
			"goals": [
				"Steal Credit Card Information"
			],
			"sophistication": "expert",
			"resource_level": "organization",
			"primary_motivation": "personal-gain"
		},
		{
			"type": "identity",
			"spec_version": "2.1",
			"id": "identity--733c5838-34d9-4fbf-949c-62aba761184c",
			"created": "2016-08-23T18:05:49.307Z",
			"modified": "2016-08-23T18:05:49.307Z",
			"name": "Disco Team",
			"description": "Disco Team is the name of an organized threat actor crime-syndicate.",
			"identity_class": "organization",
			"contact_information": "disco-team@stealthemail.com"
		},
		{
			"type": "relationship",
			"spec_version": "2.1",
			"id": "relationship--a2e3efb5-351d-4d46-97a0-6897ee7c77a0",
			"created": "2020-02-29T18:01:28.577Z",
			"modified": "2020-02-29T18:01:28.577Z",
			"relationship_type": "attributed-to",
			"source_ref": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
			"target_ref": "identity--733c5838-34d9-4fbf-949c-62aba761184c"
		}
	]
}

### Update existing (adds "hacker" to the "threat_actor_types")

POST {{BCBCTI_HostAddress}}/api/collections/default
Accept: application/taxii+json;version=2.1
Content-Type: application/taxii+json;version=2.1

{
	"objects": [
		{
			"type": "threat-actor",
			"spec_version": "2.1",
			"id": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
			"created": "2014-11-19T23:39:03.893Z",
			"modified": "2014-11-20T23:39:03.893Z",
			"name": "Disco Team Threat Actor Group",
			"description": "This organized threat actor group operates to create profit from all types of crime.",
			"threat_actor_types": [
				"crime-syndicate", "hacker"
			],
			"aliases": [
				"Equipo del Discoteca"
			],
			"roles": [
				"agent"
			],
			"goals": [
				"Steal Credit Card Information"
			],
			"sophistication": "expert",
			"resource_level": "organization",
			"primary_motivation": "personal-gain"
		}
	]
}


###

GET {{BCBCTI_HostAddress}}/api/status/18b09b0e-4b61-4901-b54f-1dcbf584426d
Accept: application/json

### 

GET {{BCBCTI_HostAddress}}/api/status/c3e56ad2-698e-4d6f-8b66-ff727793467b
Accept: application/json

###


GET {{BCBCTI_HostAddress}}/api/status/f7427f69-f0f7-4a82-9bc9-9465c52ec5b8
Accept: application/json

