@BCBCTI_HostAddress = http://localhost:5000

GET {{BCBCTI_HostAddress}}/taxii2/
Accept: application/json

###

GET {{BCBCTI_HostAddress}}/api/
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/default/manifest
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/default/manifest?added_after=2026-09-22T14:31:00Z
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/default/objects?added_after=2026-09-22T14:31:00Z
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/1e9a75e0-0a6b-412f-a445-fb050f3523b7
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/1e9a75e0-0a6b-512f-a445-fb050f3523b7
Accept: application/taxii+json;version=2.1

###

GET {{BCBCTI_HostAddress}}/api/collections/default
Accept: application/taxii+json;version=2.1

### Create new objects

POST {{BCBCTI_HostAddress}}/api/collections/default/objects
Accept: application/taxii+json;version=2.1
Content-Type: application/taxii+json;version=2.1

{
	"objects": [
		{
			"type": "threat-actor",
			"spec_version": "2.1",
			"id": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
			"created": "2014-11-19T23:39:03.893Z",
			"modified": "2014-11-19T23:39:03.893Z",
			"name": "Disco Team Threat Actor Group",
			"description": "This organized threat actor group operates to create profit from all types of crime.",
			"threat_actor_types": [
				"crime-syndicate"
			],
			"aliases": [
				"Equipo del Discoteca"
			],
			"roles": [
				"agent"
			],
			"goals": [
				"Steal Credit Card Information"
			],
			"sophistication": "expert",
			"resource_level": "organization",
			"primary_motivation": "personal-gain"
		},
		{
			"type": "identity",
			"spec_version": "2.1",
			"id": "identity--733c5838-34d9-4fbf-949c-62aba761184c",
			"created": "2016-08-23T18:05:49.307Z",
			"modified": "2016-08-23T18:05:49.307Z",
			"name": "Disco Team",
			"description": "Disco Team is the name of an organized threat actor crime-syndicate.",
			"identity_class": "organization",
			"contact_information": "disco-team@stealthemail.com"
		},
		{
			"type": "relationship",
			"spec_version": "2.1",
			"id": "relationship--a2e3efb5-351d-4d46-97a0-6897ee7c77a0",
			"created": "2020-02-29T18:01:28.577Z",
			"modified": "2020-02-29T18:01:28.577Z",
			"relationship_type": "attributed-to",
			"source_ref": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
			"target_ref": "identity--733c5838-34d9-4fbf-949c-62aba761184c"
		}
	]
}

### Update existing (adds "hacker" to the "threat_actor_types")

POST {{BCBCTI_HostAddress}}/api/collections/default/objects
Accept: application/taxii+json;version=2.1
Content-Type: application/taxii+json;version=2.1

{
	"objects": [
		{
			"type": "threat-actor",
			"spec_version": "2.1",
			"id": "threat-actor--dfaa8d77-07e2-4e28-b2c8-92e9f7b04428",
			"created": "2014-11-19T23:39:03.893Z",
			"modified": "2014-11-20T23:39:03.893Z",
			"name": "Disco Team Threat Actor Group",
			"description": "This organized threat actor group operates to create profit from all types of crime.",
			"threat_actor_types": [
				"crime-syndicate", "hacker"
			],
			"aliases": [
				"Equipo del Discoteca"
			],
			"roles": [
				"agent"
			],
			"goals": [
				"Steal Credit Card Information"
			],
			"sophistication": "expert",
			"resource_level": "organization",
			"primary_motivation": "personal-gain"
		}
	]
}


###

GET {{BCBCTI_HostAddress}}/api/status/18b09b0e-4b61-4901-b54f-1dcbf584426d
Accept: application/json

### 

GET {{BCBCTI_HostAddress}}/api/status/c3e56ad2-698e-4d6f-8b66-ff727793467b
Accept: application/json

###


GET {{BCBCTI_HostAddress}}/api/status/f7427f69-f0f7-4a82-9bc9-9465c52ec5b8
Accept: application/json


### Create (from https://oasis-open.github.io/cti-documentation/examples/indicator-for-malicious-url)

POST {{BCBCTI_HostAddress}}/api/collections/default/objects
Accept: application/taxii+json;version=2.1
Content-Type: application/taxii+json;version=2.1

{
	"objects": [
		{
			"type": "indicator",
			"spec_version": "2.1",
			"id": "indicator--d81f86b9-975b-4c0b-875e-810c5ad45a4f",
			"created": "2014-06-29T13:49:37.079Z",
			"modified": "2014-06-29T13:49:37.079Z",
			"name": "Malicious site hosting downloader",
			"description": "This organized threat actor group operates to create profit from all types of crime.",
			"indicator_types": [
				"malicious-activity"
			],
			"pattern": "[url:value = 'http://x4z9arb.cn/4712/']",
			"pattern_type": "stix",
			"valid_from": "2014-06-29T13:49:37.079Z"
		},
		{
			"type": "malware",
			"spec_version": "2.1",
			"id": "malware--162d917e-766f-4611-b5d6-652791454fca",
			"created": "2014-06-30T09:15:17.182Z",
			"modified": "2014-06-30T09:15:17.182Z",
			"name": "x4z9arb backdoor",
			"description": "This malware attempts to download remote files after establishing a foothold as a backdoor.",
			"malware_types": [
				"backdoor",
				"remote-access-trojan"
			],
			"is_family": false,
			"kill_chain_phases": [
				{
					"kill_chain_name": "mandiant-attack-lifecycle-model",
					"phase_name": "establish-foothold"
				}
			]
		},
		{
			"type": "relationship",
			"spec_version": "2.1",
			"id": "relationship--864af2ea-46f9-4d23-b3a2-1c2adf81c265",
			"created": "2020-02-29T18:03:58.029Z",
			"modified": "2020-02-29T18:03:58.029Z",
			"relationship_type": "indicates",
			"source_ref": "indicator--d81f86b9-975b-4c0b-875e-810c5ad45a4f",
			"target_ref": "malware--162d917e-766f-4611-b5d6-652791454fca"
		}
	]
}


### Create (from https://oasis-open.github.io/cti-documentation/examples/sighting-of-an-indicator)

POST {{BCBCTI_HostAddress}}/api/collections/default/objects
Accept: application/taxii+json;version=2.1
Content-Type: application/taxii+json;version=2.1

{
	"objects": [
		{
			"type": "indicator",
			"spec_version": "2.1",
			"id": "indicator--9299f726-ce06-492e-8472-2b52ccb53191",
			"created_by_ref": "identity--39012926-a052-44c4-ae48-caaf4a10ee6e",
			"created": "2017-02-27T13:57:10.515Z",
			"modified": "2017-02-27T13:57:10.515Z",
			"name": "Malicious URL",
			"description": "This URL is potentially associated with malicious activity and is listed on several blacklist sites.",
			"indicator_types": [
				"malicious-activity"
			],
			"pattern": "[url:value = 'http://paypa1.banking.com']",
			"pattern_type": "stix",
			"valid_from": "2015-06-29T09:10:15.915Z"
		},
		{
			"type": "identity",
			"spec_version": "2.1",
			"id": "identity--39012926-a052-44c4-ae48-caaf4a10ee6e",
			"created": "2017-02-24T15:50:10.564Z",
			"modified": "2017-02-24T15:50:10.564Z",
			"name": "Alpha Threat Analysis Org.",
			"roles": [
				"Cyber Security"
			],
			"identity_class": "organization",
			"sectors": [
				"technology"
			],
			"contact_information": "info@alpha.org"
		},
		{
			"type": "identity",
			"spec_version": "2.1",
			"id": "identity--5206ba14-478f-4b0b-9a48-395f690c20a2",
			"created": "2017-02-26T17:55:10.442Z",
			"modified": "2017-02-26T17:55:10.442Z",
			"name": "Beta Cyber Intelligence Company",
			"roles": [
				"Cyber Security"
			],
			"identity_class": "organization",
			"sectors": [
				"technology"
			],
			"contact_information": "info@beta.com"
		},
		{
			"type": "sighting",
			"spec_version": "2.1",
			"id": "sighting--8356e820-8080-4692-aa91-ecbe94006833",
			"created_by_ref": "identity--5206ba14-478f-4b0b-9a48-395f690c20a2",
			"created": "2017-02-28T19:37:11.213Z",
			"modified": "2017-02-28T19:37:11.213Z",
			"first_seen": "2017-02-27T21:37:11.213Z",
			"last_seen": "2017-02-27T21:37:11.214Z",
			"count": 1,
			"sighting_of_ref": "indicator--9299f726-ce06-492e-8472-2b52ccb53191",
			"where_sighted_refs": [
				"identity--5206ba14-478f-4b0b-9a48-395f690c20a2"
			]
		}
	]
}