<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <NoDefaultLaunchSettingsFile>True</NoDefaultLaunchSettingsFile>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <RootNamespace>Compellio.Bcbcti</RootNamespace>
        <Company>Compellio S.A.</Company>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.101.3" />
        <PackageReference Include="AWSSDK.S3" Version="4.0.103.2" />
        <PackageReference Include="jsoncanonicalizer" Version="1.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.12" />
        <PackageReference Include="UUIDNext" Version="4.2.4" />
    </ItemGroup>

</Project>
