services:
  bcbcti:
    image: ghcr.io/compellio/bcbcti:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BCBCTI__Storage__FileSystem__PublicBaseUrl: "https://stix.example.com/"
      RegistryAPI__ServiceUrl: "http://registry-api:8080"
      # See docs/configuration.md for more details on environment variables
    volumes:
      - bcbcti-data:/data
  
  registry-api:
    # See https://github.com/compellio/DCAP.Web for more details
    image: ghcr.io/compellio/dcap-web:latest
    environment:
      # The following configures the Registry API instance to use a local Hardhat Network
      # Replace with your own target network when you deploy.
      # WARNING: this account is publicly known: any funds sent to them on Mainnet or any other live network WILL BE LOST.
      DCAP__PrivateKey: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
      DCAP__BlockchainUrl: "http://host.docker.internal:8545/"
      DCAP__BlockchainId: "31337"
      DCAP__UriPrefix: https://example.com/dcap/ # TODO DOCUMENT -> used in TARs
    volumes:
      - registry-data:/data

volumes:
  bcbcti-data:
  registry-data:
