name: bcbcti-dcap-web-example
services:
  bcbcti:
    image: ghcr.io/compellio/bcbcti:latest
    build:
      context: ./../..
      dockerfile: Dockerfile
    depends_on: [ registry-api ]
    ports:
      - "8080:8080"
    environment:
      BCBCTI__Storage__FileSystem__PublicBaseUrl: https://stix.example.com/
      RegistryAPI__ServiceUrl: http://registry-api:8080
      BCBCTI__Ingestion__MaxConcurrentIngestions: 1
      # See docs/configuration.md for more details on environment variables
    volumes:
      - bcbcti-data:/data
  
  registry-api:
    # See https://github.com/compellio/DCAP.Web for more details
    image: ghcr.io/compellio/dcap-web:latest
    depends_on: [ anvil-blockchain ]
    environment:
      # The following configures the Registry API instance to use a local Hardhat Network
      # Replace with your own target network when you deploy.
      # WARNING: this account is publicly known: any funds sent to them on Mainnet or any other live network WILL BE LOST.
      DCAP__PrivateKey: 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
      DCAP__BlockchainUrl: http://anvil-blockchain:8545/
      DCAP__BlockchainId: 31337
      DCAP__UriPrefix: https://registry.example.com/
    volumes:
      - registry-data:/data

  anvil-blockchain:
    # Local Ethereum blockchain for testing - replace with live network when deploying
    image: ghcr.io/foundry-rs/foundry:stable
    entrypoint: [ "anvil" ]
    command: [ "--host", "0.0.0.0", "--state", "/state/anvil.json" ]
    ports:
      - "8545:8545"
    volumes:
      - anvil-state:/state

volumes:
  bcbcti-data:
  registry-data:
  anvil-state:
